Not Found: /
Not Found: /favicon.ico
Not Found: /users
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/contrib/sessions/backends/base.py", line 199, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 249, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 220, in inner
    if not self.has_permission(request):
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 194, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 224, in inner
    self._setup()
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 360, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/__init__.py", line 173, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/__init__.py", line 58, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python3.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python3.7/site-packages/django/contrib/sessions/backends/base.py", line 204, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python3.7/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/usr/local/lib/python3.7/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 411, in get
    num = len(clone)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1144, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

Not Found: /
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/contrib/sessions/backends/base.py", line 199, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 249, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 220, in inner
    if not self.has_permission(request):
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 194, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 224, in inner
    self._setup()
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 360, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/__init__.py", line 173, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/__init__.py", line 58, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python3.7/site-packages/django/contrib/sessions/backends/base.py", line 64, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python3.7/site-packages/django/contrib/sessions/backends/base.py", line 204, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python3.7/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/usr/local/lib/python3.7/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 411, in get
    num = len(clone)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1144, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

Not Found: /
Not Found: /admin/login/static/admin/css/base.css
Not Found: /admin/login/static/admin/css/responsive.css
Not Found: /admin/login/static/admin/css/login.css
Not Found: /admin/login/static/admin/css/responsive.css
Not Found: /admin/login/static/admin/css/base.css
Not Found: /admin/login/static/admin/css/login.css
Not Found: /users
Not Found: /admin/login/static/admin/css/login.css
Not Found: /admin/login/static/admin/css/base.css
Not Found: /admin/login/static/admin/css/responsive.css
Not Found: /admin/login/static/admin/css/base.css
Not Found: /admin/login/static/admin/css/responsive.css
Not Found: /admin/login/static/admin/css/login.css
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /favicon.ico
Not Found: /main.51b9a7b39d9fdbef0e83.hot-update.json
Not Found: /img/logo.svg
Not Found: /img/logo.svg
Not Found: /img/logo.svg
Not Found: /img/logo.svg
Not Found: /img/logo.svg
Not Found: /img/logo.svg
Not Found: /img/logo.svg
Not Found: /img/logo.svg
Not Found: /img/logo.svg
Not Found: /
Not Found: /favicon.ico
Not Found: /resources/illustrations/
Not Found: /resources/illustrations/landing_fitness_tracker.svg
Not Found: /resources/illustrations/landing_fitness_tracker.svg
Not Found: /resources/illustrations/landing_fitness_tracker
Not Found: /resources/illustrations/landing_fitness_tracker
Not Found: /resources/illustrations/landing_fitness_tracker
Not Found: /resources/illustrations/landing_fitness_tracker.svg
Not Found: /landing_fitness_tracker.svg
Not Found: /landing_fitness_tracker.svg
Not Found: /landing_fitness_tracker.svg
Not Found: /landing_fitness_tracker.svg
Not Found: /landing_fitness_tracker.svg
Not Found: /landing_fitness_tracker.svg
Not Found: /landing_fitness_tracker.svg
Not Found: /landing_fitness_tracker.svg
Not Found: /landing_fitness_tracker.svg
Not Found: /resources/illustrations/landing_fitness_tracker.svg
Not Found: /resources/illustrations/landing_fitness_tracker.svg
Not Found: /src/resources/illustrations/landing_fitness_tracker.svg
Not Found: /src/resources/illustrations/landing_fitness_tracker.svg
Not Found: /src/resources/illustrations/landing_fitness_tracker.svg
Not Found: /src/resources/illustrations/landing_fitness_tracker.svg
Not Found: /src/resources/illustrations/landing_fitness_tracker.svg
Not Found: /src/resources/illustrations/landing_fitness_tracker.svg
Not Found: /src/resources/illustrations/landing_fitness_tracker.svg
Not Found: /src/resources/illustrations/landing_fitness_tracker.svg
Not Found: /src/resources/illustrations/landing_fitness_tracker.svg
Not Found: /src/resources/illustrations/landing_fitness_tracker.svg
Not Found: /src/resources/illustrations/landing_fitness_tracker.svg
Not Found: /src/resources/illustrations/landing_fitness_tracker.svg
Not Found: /resources/illustrations/landing_fitness_tracker.svg
Not Found: /src/resources/illustrations/landing_fitness_tracker.svg
Not Found: /src/resources/illustrations/landing_fitness_tracker.svg
Not Found: /src/resources/illustrations/landing_fitness_tracker.svg
Not Found: /src/resources/illustrations/landing_fitness_tracker.svg
Not Found: /src/resources/illustrations/landing_fitness_tracker.svg
Not Found: /src/resources/illustrations/landing_fitness_tracker.svg
Not Found: /
Not Found: /favicon.ico
Not Found: /main.cf8925f6b06d6ad9ccf7.hot-update.json
